language: ruby
rvm:
- 2.1.2
script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create db:migrate
- bundle exec rspec spec
deploy:
  provider: heroku
  api_key:
    secure: TRj/gIlmCuGiHGjzXOw3QJm/hhtZpO+j2oDVwoedQdTSvUQ3rJl5DKw2e1aAG6Qc2WNkcVnah2rHG1pRtj5J+Sk4x1SVC8FBQ5Sn83Fu1g2h0aB0NgTZPTbmBLHio/248f9BcJ7rm51rbqwgNeljezenb6hagMr6+8YVS6w3VH4=
  app: peaceful-sea-4129
  on:
    repo: vpfaulkner/Compass
