language: ruby
rvm:
  - "2.1.2"
# uncomment this line if your project needs to run something other than `rake`:
script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate
  - bundle exec rspec spec
deploy:
  provider: heroku
  app: peaceful-sea-4129 # optional if it's the same as your repo name
  HEROKU_KEY: "cBjgzJ1TVtFGDbP+aSLKCpQ2LGWr0XU44QzKrhZe4NuS3PlLbbh7vmaGzCyubyuch/5w0ggzXoFihfsziwO6/ozGRd1pBuZoyvFkh3Y3ttWnb06ZvBWlR85wTkUIt9oIjqyqNKFYWox8BxMymCvf1oBEKsLLYc3ADE+K4ujBvHI="
